version: '3.5'

networks:
  default:
    external:
      name: FG_net

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}"
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      default:
        ipv4_address: ${IP_ELASTIC}

  logstash:
    image: "docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}"
    container_name: logstash
    hostname: logstash
    restart: always
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      default:
        ipv4_address: ${IP_LOGSTASH}
    depends_on:
      - elasticsearch

  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}"
    container_name: kibana
    hostname: kibana
    restart: always
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      static-network:
        ipv4_address: ${IP_KIBANA}
    depends_on:
      - elasticsearch